import Anthropic from "@anthropic-ai/sdk";

interface Candidate {
  id: string;
  name: string;
  title: string;
  company: string;
  location: string;
}

interface CampaignContext {
  role_title: string;
  role_description: string;
  ideal_candidate_profile?: string;
}

interface MessageResponse {
  message: string;
  reasoning: string;
  tokens_used: number;
}

export class ClaudeClient {
  private client: Anthropic;

  constructor(apiKey: string) {
    this.client = new Anthropic({ apiKey });
  }

  async generateMessage(
    candidate: Candidate,
    campaign?: CampaignContext
  ): Promise<MessageResponse> {
    try {
      let campaignSection = "";
      if (campaign) {
        campaignSection = `
Role we're hiring for: ${campaign.role_title}
Role description: ${campaign.role_description}
${campaign.ideal_candidate_profile ? `Ideal candidate: ${campaign.ideal_candidate_profile}` : ""}
`;
      }

      const prompt = `You are a recruiter helping to find candidates on LinkedIn.

Generate a personalized LinkedIn connection request note for this candidate:

Name: ${candidate.name}
Title: ${candidate.title}
Company: ${candidate.company}
Location: ${candidate.location}
${campaignSection}
Requirements:
- Keep it concise (50-100 words) — this is a connection request note, NOT an InMail
- Be professional but friendly
- Reference their specific background
- ${campaign ? `Tie it to why they'd be great for the ${campaign.role_title} role` : "Make it clear why you're reaching out"}
- Don't sound generic or templated
- Don't use phrases like "I came across your profile"

Return a JSON object with:
{
  "message": "the connection request note",
  "reasoning": "brief explanation of why this message works for this candidate"
}`;

      const response = await this.client.messages.create({
        model: "claude-sonnet-4-5-20250929",
        max_tokens: 500,
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
      });

      let content =
        response.content[0].type === "text" ? response.content[0].text : "";

      // Strip markdown code fences if present (```json ... ```)
      content = content.replace(/^```(?:json)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim();

      try {
        const parsed = JSON.parse(content);
        return {
          message: parsed.message,
          reasoning: parsed.reasoning,
          tokens_used: response.usage.output_tokens,
        };
      } catch (e) {
        return {
          message: content,
          reasoning: "Generated by Claude",
          tokens_used: response.usage.output_tokens,
        };
      }
    } catch (error) {
      console.error("Claude API error:", error);
      throw error;
    }
  }
}
