import Anthropic from "@anthropic-ai/sdk";

interface Candidate {
  id: number;
  name: string;
  title: string;
  company: string;
  location: string;
}

interface MessageResponse {
  message: string;
  reasoning: string;
  tokens_used: number;
}

export class ClaudeClient {
  private client: Anthropic;

  constructor(apiKey: string) {
    this.client = new Anthropic({ apiKey });
  }

  async generateMessage(candidate: Candidate): Promise<MessageResponse> {
    try {
      const prompt = `You are a recruiter helping to find candidates on LinkedIn.

Generate a personalized LinkedIn message for this candidate:

Name: ${candidate.name}
Title: ${candidate.title}
Company: ${candidate.company}
Location: ${candidate.location}

Requirements:
- Keep it concise (50-100 words)
- Be professional but friendly
- Reference their background
- Make it clear why you're reaching out
- Don't sound generic

Return a JSON object with:
{
  "message": "the message text",
  "reasoning": "brief explanation of why this message works"
}`;

      const response = await this.client.messages.create({
        model: "claude-3-5-sonnet-20241022",
        max_tokens: 500,
        messages: [
          {
            role: "user",
            content: prompt,
          },
        ],
      });

      const content =
        response.content[0].type === "text" ? response.content[0].text : "";

      try {
        const parsed = JSON.parse(content);
        return {
          message: parsed.message,
          reasoning: parsed.reasoning,
          tokens_used: response.usage.output_tokens,
        };
      } catch (e) {
        // Fallback if JSON parsing fails
        return {
          message: content,
          reasoning: "Generated by Claude",
          tokens_used: response.usage.output_tokens,
        };
      }
    } catch (error) {
      console.error("Claude API error:", error);
      throw error;
    }
  }

  async analyzeProfile(profileData: Record<string, any>): Promise<string> {
    // TODO: Implement profile analysis
    return "Profile analysis not yet implemented";
  }
}
