import TelegramBot, { InlineKeyboardMarkup } from "node-telegram-bot-api";

interface ApprovalNotification {
  id: number;
  candidate_name: string;
  candidate_title: string;
  candidate_company: string;
  linkedin_url: string;
  proposed_text: string;
  context: string;
  approval_type: string;
}

let botInstance: TelegramBot | null = null;
let notifyChatIds: number[] = [];

export function initNotifier(bot: TelegramBot, chatIds: number[]) {
  botInstance = bot;
  notifyChatIds = chatIds;
}

export async function sendApprovalNotification(approval: ApprovalNotification) {
  if (!botInstance) {
    throw new Error("Notifier not initialized. Call initNotifier first.");
  }

  const titleLine = [approval.candidate_title, approval.candidate_company]
    .filter(Boolean)
    .join(" @ ");

  const message =
    `🎯 ${approval.candidate_name}\n` +
    (titleLine ? `📍 ${titleLine}\n` : "") +
    `🔗 ${approval.linkedin_url}\n\n` +
    `💬 Message:\n"${approval.proposed_text}"\n\n` +
    (approval.context && approval.context !== "Generated by Claude"
      ? `🤖 ${approval.context}`
      : "");

  const keyboard: InlineKeyboardMarkup = {
    inline_keyboard: [
      [
        { text: "✅ Approve", callback_data: `approve:${approval.id}` },
        { text: "❌ Skip", callback_data: `skip:${approval.id}` },
        { text: "⏸️ Pause", callback_data: `pause:${approval.id}` },
      ],
    ],
  };

  for (const chatId of notifyChatIds) {
    await botInstance.sendMessage(chatId, message, {
      reply_markup: keyboard,
    });
  }

  console.log(
    `📨 Approval request sent to ${notifyChatIds.length} user(s) for ${approval.candidate_name}`
  );
}
