"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { getApiClient } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import type { Approval } from "@/lib/types";

const statusVariant: Record<string, "warning" | "info" | "danger" | "success" | "default"> = {
  pending: "warning",
  approved: "info",
  rejected: "danger",
  sent: "success",
  failed: "danger",
};

const statuses = ["", "pending", "approved", "rejected", "sent", "failed"];

export default function ApprovalsPage() {
  const api = getApiClient();
  const queryClient = useQueryClient();
  const [statusFilter, setStatusFilter] = useState("pending");

  const { data: approvals, isLoading } = useQuery<Approval[]>({
    queryKey: ["approvals", { status: statusFilter }],
    queryFn: () =>
      api.get("/api/approvals", { params: statusFilter ? { status: statusFilter } : {} }).then((r) => r.data),
  });

  const updateApproval = useMutation({
    mutationFn: ({ id, status }: { id: string; status: string }) =>
      api.patch(`/api/approvals/${id}`, { status }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["approvals"] });
    },
  });

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-3xl font-bold text-gray-900">Approval Queue</h1>
        <Select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
        >
          <option value="">All</option>
          {statuses.filter(Boolean).map((s) => (
            <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>
          ))}
        </Select>
      </div>

      <div className="bg-white rounded-lg shadow overflow-hidden">
        {isLoading ? (
          <div className="p-6 text-center text-gray-500">Loading...</div>
        ) : !approvals || approvals.length === 0 ? (
          <div className="p-6 text-center text-gray-500">No approvals found.</div>
        ) : (
          <div className="divide-y divide-gray-200">
            {approvals.map((a) => (
              <div key={a.id} className="px-6 py-4">
                <div className="flex justify-between items-start">
                  <div className="flex-1">
                    <div className="flex items-center gap-3">
                      <p className="font-medium text-gray-900">{a.candidate_name}</p>
                      <Badge variant={statusVariant[a.status] ?? "default"}>{a.status}</Badge>
                      <span className="text-xs text-gray-400">{a.approval_type}</span>
                    </div>
                    <p className="text-sm text-gray-500 mt-0.5">
                      {[a.candidate_title, a.candidate_company].filter(Boolean).join(" @ ")}
                    </p>
                    <p className="text-sm text-gray-600 mt-2 bg-gray-50 rounded p-3">
                      &ldquo;{a.proposed_text}&rdquo;
                    </p>
                    {a.context && a.context !== "Generated by Claude" && (
                      <p className="text-xs text-gray-400 mt-1">{a.context}</p>
                    )}
                  </div>

                  {a.status === "pending" && (
                    <div className="flex gap-2 ml-4 flex-shrink-0">
                      <Button
                        size="sm"
                        variant="success"
                        onClick={() => updateApproval.mutate({ id: a.id, status: "approved" })}
                        disabled={updateApproval.isPending}
                      >
                        Approve
                      </Button>
                      <Button
                        size="sm"
                        variant="destructive"
                        onClick={() => updateApproval.mutate({ id: a.id, status: "rejected" })}
                        disabled={updateApproval.isPending}
                      >
                        Reject
                      </Button>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
